### ISSUE TITLE
没有设置X轴标尺数据的方法吗

### ISSUE THREAD

**Issue by SerbiaKelly** [monitor1394/unity-ugui-XCharts#10]
![image](https://user-images.githubusercontent.com/38457609/61354973-ed8cab00-a8a5-11e9-865e-ae97105a406c.png)
希望有设置这个的接口方法

**Comment by monitor1394** [comment]
参考Demo10_LineSimple.cs
可以用`chart.AddXAxisData()`或`chart.AddYAxisData()`给Axis添加数据
