### ISSUE TITLE
纵向折线图如果类型是smooth，容易报数组下标越界的错误

### ISSUE THREAD

**Issue by PHNoob** [monitor1394/unity-ugui-XCharts#100]
1. 生成一个新的LineChart，交换xy轴。
![image](https://user-images.githubusercontent.com/49261291/97834557-1cd16080-1d13-11eb-8441-9a43aef386f3.png)

2. 将该折线图的类型改为smooth，其余配置项均默认。
![image](https://user-images.githubusercontent.com/49261291/97834608-34a8e480-1d13-11eb-9cd6-3e6361c2d744.png)

3. 添加200个点(实际上一百多个点就会报错)，如下图。
![image](https://user-images.githubusercontent.com/49261291/97834695-65891980-1d13-11eb-8089-cd2285e94baf.png)

4. 有很大的概率报数组下标越界的错误。
![image](https://user-images.githubusercontent.com/49261291/97834738-82bde800-1d13-11eb-9ab3-baa8e81b4300.png)
![image](https://user-images.githubusercontent.com/49261291/97834752-8a7d8c80-1d13-11eb-8755-7935c2eb375d.png)

5. 只有smooth类型会报错，其他类型如Normal、Dot等都没有问题。

6. 如果不对y轴进行添加category的操作，则不会下标越界。
![image](https://user-images.githubusercontent.com/49261291/97835074-4939ac80-1d14-11eb-96eb-36ee33f11a10.png)

**Comment by monitor1394** [comment]
已修复。
