### ISSUE TITLE
Support for TMP

### ISSUE THREAD

**Issue by psarras** [monitor1394/unity-ugui-XCharts#102]
It would be useful to add support for Text Mesh Pro, as this is the recommended method for displaying text in Unity. Text seems a bit blurry at the moment.

**Comment by monitor1394** [comment]
I don't have any experience in this field. What should I do about it? Is there any information on how to support TMP?

**Comment by psarras** [comment]
Thanks for your comment. I think there are probably two pathways. 1) Drop support for the the legacy Text system, or 2) Create a hybrid that supports both. Unity is now shipping by default with Text Mesh Pro, and I don't think there is any drawback using just TMP. [Blog post about TMP](https://blogs.unity3d.com/2018/10/16/making-the-most-of-textmesh-pro-in-unity-2018/). Otherwise you can have a toggle like in the image below when you support either platform.

These are from the plugin [Doozy](https://assetstore.unity.com/packages/tools/gui/doozyui-complete-ui-management-system-138361).
![image](https://user-images.githubusercontent.com/3820417/99872349-23981880-2bd9-11eb-8ee4-6f411e23384a.png)

![image](https://user-images.githubusercontent.com/3820417/99872354-2d218080-2bd9-11eb-838e-b3d6224a3bc4.png)

**Comment by monitor1394** [comment]
Thank you for your advice. It helps me a lot.
TextMeshPro is already supported in XCharts 2.0, but has not yet been released.
XCharts 2.0 has a lot of work to do but is almost done.

**Comment by psarras** [comment]
@monitor1394 This is great! Is there an ETA for 2.0?

**Comment by monitor1394** [comment]
I try my best to release XCharts 2.0 before The New Year's Day of 2021.

**Comment by monitor1394** [comment]
The master branch is XCharts2.0 now. The release version will be released in these days.
