### ISSUE TITLE
可以抛弃原来的ttf使用unity新版的TMP字体文件么

### ISSUE THREAD

**Issue by seriousuncle** [monitor1394/unity-ugui-XCharts#105]
如上

**Comment by monitor1394** [comment]
后续版本会考虑支持TMP

**Comment by seriousuncle** [comment]
自己可以修改么，如果可以，难度怎么样呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "monitor1394/unity-ugui-XCharts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 晚上8:30
收件人:&nbsp;"monitor1394/unity-ugui-XCharts"<unity-ugui-XCharts@noreply.github.com&gt;;
抄送:&nbsp;"骨子里"<962674577@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [monitor1394/unity-ugui-XCharts] 可以抛弃原来的ttf使用unity新版的TMP字体文件么 (#105)





 
后续版本会考虑支持TMP

**Comment by monitor1394** [comment]
master已是2.0版本，2.0版本支持TextMeshPro。
