### ISSUE TITLE
折线图 支持这种表现效果么？

### ISSUE THREAD

**Issue by anshawuqing** [monitor1394/unity-ugui-XCharts#107]
![image](https://user-images.githubusercontent.com/29351503/103150245-3b048b80-47ad-11eb-81fc-5898ec01e3d3.png)
就是 折线的节点 到坐标轴之间有线段连接的效果

**Comment by monitor1394** [comment]
不支持直接设置。
但可以通过其他途径实现，再加一个bar类型的serie，width设的很小，BarType设置为Zebar，也可以实现类型的效果。
<img width="312" alt="image" src="https://user-images.githubusercontent.com/1450329/103173756-1c2ef380-4898-11eb-9d8e-56f5dd82ccfc.png">
