### ISSUE TITLE
在使用坐标的时候出现刻度均分出错的情况

### ISSUE THREAD

**Issue by ConanGentleman** [monitor1394/unity-ugui-XCharts#108]
在unity中
>
>添加LineChart并点击  
-> 查看Inspector中的Y Axis 0 
->Type选择value
->Min Max Type 设置为custom
-> Min 设置为负数（如-0.2） Max设置为正数（如1.2）
->Split Number设置为5
->！！！！则在刻度为0处的刻度值为0.0800001 其余刻度正常！！！！

希望对于上述问题进行修改 ， 非常感谢！

插件非常好用  支持 加油！

**Comment by monitor1394** [comment]
浮点数计算问题。建议通过AxisLabel的NumericFormatter指定浮点数精度，如f2。

**Comment by ConanGentleman** [comment]
好的我试试谢谢！
