### ISSUE TITLE
可以增加滚动X轴的功能吗？

### ISSUE THREAD

**Issue by liuyichuan** [monitor1394/unity-ugui-XCharts#109]
X轴data太多，可以增加一个选项自动延申X轴长度，超出整个图表宽度自动增加滚动条的功能。
但是Y轴要固定不能被一起滚动。我正在尝试。

**Comment by monitor1394** [comment]
可以用DataZoom

**Comment by liuyichuan** [comment]
DataZoom开启后会导致下方X轴缩放比例不对，没办法和serie数据对齐，仅测试了柱状图下

**Comment by monitor1394** [comment]
数据太少没必要了，可以自己将chart放到scrollview里。

**Comment by liuyichuan** [comment]
好的，大概明白了。顺便问下大佬，2.0大概啥时候上呢，很期待！

**Comment by monitor1394** [comment]
`XCharts2.0.0-preview1` 预览版 已经放群里测试了，没啥大问题这两天会提交到github。
