### ISSUE TITLE
请问如何单独调整折线图中某个label的字体颜色

### ISSUE THREAD

**Issue by SSB4455** [monitor1394/unity-ugui-XCharts#111]
折线图设置了Label显示
在Serie中data选择more
对某个label单独调整颜色不产生效果 
请问我该如何单独调整某个label的字体颜色呢 
感谢

**Comment by monitor1394** [comment]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/1450329/104406129-897d9c80-5599-11eb-98bc-ef3c9e496b0c.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/1450329/104406152-9601f500-5599-11eb-81f5-b5ac8ba4598b.png">

**Comment by SSB4455** [comment]
原来要两个都勾选
真是太感谢了
