### ISSUE TITLE
如何对鼠标当前选择的数据进行交互？

### ISSUE THREAD

**Issue by SadasyKing** [monitor1394/unity-ugui-XCharts#112]
请问一下，目前我在使用柱状图BarChart，该表格内有多个数据。我需要在鼠标指向某个数据提示Tooltip时，点击该数据并进行交互，应该如何操作呢？

**Comment by monitor1394** [comment]
设置onPointerClickBar回调

**Comment by SadasyKing** [comment]
您好，我有查看您给出的文档的
当我定义了一个类mybarchart并且继承了barchart后，override里没有找到这个方法，只找到了没有bar后缀的基于graphic类的回调函数。包括基于unity2019.4的最新版本的xchart也是

**Comment by SadasyKing** [comment]
您好，我有查看您给出的文档的
当我定义了一个类mybarchart并且继承了barchart后，override里没有找到这个方法，只找到了没有bar后缀的基于graphic类的回调函数。包括基于unity2019.4的最新版本的xchart也是

**Comment by SadasyKing** [comment]
您好，我有查看您给出的文档的
当我定义了一个类mybarchart并且继承了barchart后，override里没有找到这个方法，只找到了没有bar后缀的基于graphic类的回调函数。包括基于unity2019.4的最新版本的xchart也是

**Comment by monitor1394** [comment]
public类型的，肯定有。

**Comment by SadasyKing** [comment]
好的好的，那我再看看。
我查阅了最新版的源代码确实有这个，但是调用不到。有点昏头了

**Comment by SadasyKing** [comment]
我主要使用的是1.0.1版本的XChart配合Unity2018，应该确实没有OnPointerClickBar，只有OnPointerClick函数调用。
最新版本的XChart没法放到2018使用，很多报错=，=

**Comment by SadasyKing** [comment]
我目前使用了1.6.2版本，找到了OnPointerClickBar的定义，但是在继承了BarChart类后还是无法调用到……
请问应该如何调用呢

**Comment by SadasyKing** [comment]
您好，我找到一个解决方案：
通过查看您的源码，发现您在BarChart中重写了OnPointerDown方法。在这个全新的方法中，您使用了一个“m_Tooltip.runtimeDataIndex[0]”属性，我在自己的OnPointerClick方法中输出了这个属性，发现如我所点击的一般，输出了相应的柱状图在数据中的下标

**Comment by monitor1394** [comment]
你这种方案也可以，但不是很建议这样做，因为内部的源码可能随着版本更新和优化被改掉或删掉。

可以这样调用：
![image](https://user-images.githubusercontent.com/1450329/104537925-d626ad80-5655-11eb-91c3-26c5f2579b04.png)

**Comment by SadasyKing** [comment]
收到！测试成功！感谢您的帮助！
