### ISSUE TITLE
Align With Label

### ISSUE THREAD

**Issue by QiJiShan** [monitor1394/unity-ugui-XCharts#115]
![2C@ 5(CM4E1G1%`1%%TUOSS](https://user-images.githubusercontent.com/75008579/106123954-8687cc00-6195-11eb-9b35-c309f326a9f7.png)
![{9}_P{)UP7CGP{IQLHEDCD7](https://user-images.githubusercontent.com/75008579/106123979-8be51680-6195-11eb-9296-ccfd9b44de7a.png)
我选了这个属性之后 为啥最后一个下标没有居中呢

**Comment by QiJiShan** [comment]
图片好像是没显示出来吗？
X Axis 0 -> Axis Tick -> Align With Label 就是这个选项选中之后 最后一个下标并没有剧中

**Comment by monitor1394** [comment]
图片能看到，是bug，晚点处理。
