### ISSUE TITLE
饼图数据间差距较大时，数据小的模块看不见

### ISSUE THREAD

**Issue by 113377961** [monitor1394/unity-ugui-XCharts#117]
饼图数据间差距较大时，数据小的模块看不见

**Comment by monitor1394** [comment]
你的配置是怎样的？设置了border？你要什么样的效果？给参考图。

**Comment by 113377961** [comment]
感谢您的回复，效果图给您看下，标注部分数值比较小，现在想实现类似Echarts里面最小角度，来保证它可以正常显示，不知XCharts里在哪设置。



113377961@163.com
 
发件人： monitor1394
发送时间： 2021-02-03 12:55
收件人： monitor1394/unity-ugui-XCharts
抄送： 113377961; Author
主题： Re: [monitor1394/unity-ugui-XCharts] 问题 (#117)
你的配置是怎样的？设置了border？你要什么样的效果？给参考图。

**Comment by monitor1394** [comment]
ECharts的minAngle是吧

**Comment by monitor1394** [comment]
master已支持minAngle
