### ISSUE TITLE
2.0复制Chart时Theme不能单独设置

### ISSUE THREAD

**Issue by shenhuilin** [monitor1394/unity-ugui-XCharts#118]
修改了Theme里面的参数会导致同类型图表里面的Theme都是一样的参数。

**Comment by monitor1394** [comment]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/1450329/111918198-f09a5e80-8abe-11eb-8c46-3fb5cd5355d7.png">
增加了解绑的按钮，目前需要手动处理一下。

**Comment by monitor1394** [comment]
主题已重构，导出的主题改用json存储，更新后旧的主题设置可能会被还原为Default主题。

**Comment by Bian-Sh** [comment]
可以参考material 的特性：
