### ISSUE TITLE
Chart breaks with Vertical Layout Group

### ISSUE THREAD

**Issue by psarras** [monitor1394/unity-ugui-XCharts#121]
So I have observed this behaviour which I am not sure how to overcome.

- Canvas
  - Vertical Layout Group
    - Chart1
    - Chart2
    - ...

So if you structure your game objects like so, using Ctrl+D to duplicate the chart, one of them would leave its text behind...

![image](https://user-images.githubusercontent.com/3820417/108078688-e28f9300-7065-11eb-9bc4-a5553a772ec0.png)
![image](https://user-images.githubusercontent.com/3820417/108078709-e7544700-7065-11eb-93ae-6efed866c0f1.png)

I've been also trying to do it a much more nested situation than that and it is a total mess, I have to manually refresh the components from the editor and sometimes it gets fixed...

**Comment by monitor1394** [comment]
Is it normal at run time?

**Comment by monitor1394** [comment]
It has been confirmed that this is a bug and will be fixed later.

**Comment by monitor1394** [comment]
This issue has been fixed in the master branch.
