### ISSUE TITLE
Lost TMP reference on the new version?

### ISSUE THREAD

**Issue by psarras** [monitor1394/unity-ugui-XCharts#125]
I think this must be due to this commit:

https://github.com/monitor1394/unity-ugui-XCharts/commit/4ea5168e9ae6ebe466d6de5733a5131a7db48d85

Trying to update today and it was missing TMP references

![image](https://user-images.githubusercontent.com/3820417/109286369-0d25dc80-781a-11eb-9429-4a740a4ba6a6.png)

**Comment by monitor1394** [comment]
I fixed it in master.
Given that TMP is not enabled by default, so asmdef does not added a reference to TMP at first, but automatically added when TMP enabled.

**Comment by psarras** [comment]
Awesome will try it on Monday! Cheers!

**Comment by psarras** [comment]
Hey! I think there is an unforeseen bug here. The button Enable TMP will not work if you have compile errors. An while updating, I am removing and adding the library, which causes to have compile errors since the moment the package comes in doesn't have any references to TMP. Is there a way to import it directly with TMP, or avoid having those temporary compile errors?

**Comment by monitor1394** [comment]
You need to work out those compilation errors yourself. 

Manually remove dUI_TextMeshPro:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/1450329/109641150-5a90a980-7b8c-11eb-8f8b-5812da25181b.png">

When the compilation is successful, you can press the UI button Enable TMP to import TMP again.

**Comment by psarras** [comment]
Hey @monitor1394 I've updated my comment. The errors are from the library. I did as you said! Cheers.

**Comment by monitor1394** [comment]
I have pushed the modification of master to the 2.0-UPM branch, and the test is OK.

**Comment by psarras** [comment]
Works as expected! Awesome work 👍

**Comment by psarras** [comment]
Ok this works on my machine quite well and I can build. However when I try this project on a CI/CD pipeline I get the same errors. I guess this is because I need to call the TextMeshPro Enable before compiling, in order to get the TMP reference. Is there a way to do that you think?

**Comment by monitor1394** [comment]
See if I understand you right:
The project on CI/CD is the same git or SVN as your local project. Then you push the projectSetting.asset with the DUI_TextMeshPro. But ASMDEF can't synchronize.
The result is that the project found on the CI/CD requires TMP but the local ASMDEF does not have a reference to TMP.
Is that right?

If so, there seems to be a problem. Do you have any suggestions?

**Comment by psarras** [comment]
Yep that is correct. I haven't thought any satisfactory solution yet I am afraid.

I can include this library in my Assets folder and then I would be able to push the right ASMDEF but this is not pretty. Or I can fork it and include on the fork this reference again.

Is there a way to have multiple package releases, one with TMP and one without? But this also sounds weird. It needs more investigation from my end at least.

**Comment by monitor1394** [comment]
I haven't thought any satisfactory solution yet.

I also think this is an option:

> Is there a way to have multiple package releases, one with TMP and one without?

**Comment by cLick1338** [comment]
Reiterating the solution that worked for me in case other people need it: (Local editor and build, not using CI/CD)
Project Settings -> Player : Scripting Define Symbols -> Remove dUI_TextMeshPro
XCharts dropdown menu (top of Unity window) -> TextMeshPro Enable

**Comment by nixcry** [comment]
Still have this issue with XCharts v2.1.1
Environment:
Unity 2019.4.11,
TextMeshPro 2.1.6
Unity UI 1.0.0

Solution: 
Fell back to XCharts v2.0.0, the problem fixed, working with TextMeshPro again.
> I think this must be due to this commit:
> 
> [4ea5168](https://github.com/monitor1394/unity-ugui-XCharts/commit/4ea5168e9ae6ebe466d6de5733a5131a7db48d85)
> 
> Trying to update today and it was missing TMP references
> 
> ![image](https://user-images.githubusercontent.com/3820417/109286369-0d25dc80-781a-11eb-9429-4a740a4ba6a6.png)

**Comment by JimZeeKing** [comment]
> 
> 
> Still have this issue with XCharts v2.1.1
> Environment:
> Unity 2019.4.11,
> TextMeshPro 2.1.6
> Unity UI 1.0.0
> 
> Solution:
> Fell back to XCharts v2.0.0, the problem fixed, working with TextMeshPro again.
> 
> > I think this must be due to this commit:
> > [4ea5168](https://github.com/monitor1394/unity-ugui-XCharts/commit/4ea5168e9ae6ebe466d6de5733a5131a7db48d85)
> > Trying to update today and it was missing TMP references
> > ![image](https://user-images.githubusercontent.com/3820417/109286369-0d25dc80-781a-11eb-9429-4a740a4ba6a6.png)

Same for me
