### ISSUE TITLE
Enabling and disabling a Chart causes extra Indicators to appear?

### ISSUE THREAD

**Issue by psarras** [monitor1394/unity-ugui-XCharts#127]
So this is a bit weird...

I created a prefab with a RadarChart component.
I am overriding the data at some point during runtime. It is worth noting that the default data  might had 5 indicators.
Then I manually enable / Disable the parent or the Chart itself and I get those two extra indicators appear....

![image](https://user-images.githubusercontent.com/3820417/109299415-fa68d300-782c-11eb-8250-b866f5d02111.png)

The weird thing is that on the inspector, I am getting this:

![image](https://user-images.githubusercontent.com/3820417/109299575-3a2fba80-782d-11eb-9d20-e3dd533beb60.png)

I think this is fixable if you click the "remove All Chart Objects" before saving the prefab. But shouldn't this be the automatic behaviour when you RemoveData(); on the chart?

Now I am fixing this by making sure the prefab has zero data / "Remove All Chart Objects" has been clicked. and then I am calling both RemoveData and RemoveChartObject. Let me know what you think. :)

**Comment by monitor1394** [comment]
Yes, it's designed to refresh chart automatically when removeData () is called, so you don't have to manually call removeChartObject ().

Maybe this is a bug and I need to test and confirm it.
Could you show me the code snippet where you override the data?

**Comment by monitor1394** [comment]
Confirmed as a bug and I will fix it ASAP.

**Comment by monitor1394** [comment]
Fixed in master branch.
