### ISSUE TITLE
Animation not working for Radar Charts.

### ISSUE THREAD

**Issue by TheAuteur** [monitor1394/unity-ugui-XCharts#13]
Hi, 

I'm using version 0.8.3 and the animation for radar chart is not working, even after it is enabled in the editor.

**Comment by monitor1394** [comment]
Thanks for your feedback. 
The radar chart does not support animation yet, it will be supported in version 1.0, which will be released soon.

**Comment by monitor1394** [comment]
radar chart animation is already supported in the master branch.

**Comment by TheAuteur** [comment]
Ok, will check it out. Thank you.
