### ISSUE TITLE
柱状图的鼠标点击事件

### ISSUE THREAD

**Issue by fashionguy** [monitor1394/unity-ugui-XCharts#130]
感谢分享。
我在使用柱状图，我希望点击某个数据，触发点击事件，将点击的数据值作为参数传递给触发事件。
我看到柱状图的鼠标点击事件chart.onPointerClick = OnPointerClick，无法完成这个需求。
您有什么建议么。

**Comment by monitor1394** [comment]
![image](https://user-images.githubusercontent.com/1450329/113648141-b59f4a00-96be-11eb-8f86-9c00a36000f1.png)

**Comment by fashionguy** [comment]
好的谢谢
