### ISSUE TITLE
XCharts.ChartTheme is missing class attribute 'ExtensionOfNativeClass'

### ISSUE THREAD

**Issue by lodlock** [monitor1394/unity-ugui-XCharts#131]
After updating to 2.1 I've started receiving this error on start:

`'XCharts.ChartTheme' is missing the class attribute 'ExtensionOfNativeClass'!`

**Comment by monitor1394** [comment]
Thanks for your feedback.
I have fixed the problem in the master branch. 
A new release version will be released later.
