### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by becker88** [monitor1394/unity-ugui-XCharts#137]
1. NullReferenceException: Object reference not set to an instance of an object
XCharts.BaseChart.GetPainterIndexBySerie (XCharts.Serie serie) (at Assets/XCharts/Runtime/Internal/BaseChart.cs:1017)
XCharts.BaseChart.RefreshPainter (XCharts.Serie serie) (at Assets/XCharts/Runtime/Internal/BaseChart.cs:181)
XCharts.BaseChart.AddData (System.Int32 serieIndex, System.Single data, System.String dataName) (at Assets/XCharts/Runtime/API/BaseChart_API.cs:233)

2. NullReferenceException: Object reference not set to an instance of an object
XCharts.BaseChart.GetPainterIndexBySerie (XCharts.Serie serie) (at Assets/XCharts/Runtime/Internal/BaseChart.cs:1017)
XCharts.BaseChart.RefreshPainter (XCharts.Serie serie) (at Assets/XCharts/Runtime/Internal/BaseChart.cs:181)
XCharts.BaseChart.CheckComponent () (at Assets/XCharts/Runtime/Internal/BaseChart.cs:243)
XCharts.BaseGraph.Update () (at Assets/XCharts/Runtime/Internal/BaseGraph.cs:102)
XCharts.BaseChart.Update () (at Assets/XCharts/Runtime/Internal/BaseChart.cs:150)
XCharts.CoordinateChart.Update () (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:48)

3. NullReferenceException: Object reference not set to an instance of an object
XCharts.CoordinateChart.UpdateAxisMinMaxValue (System.Int32 axisIndex, XCharts.Axis axis, System.Boolean updateChart) (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:898)
XCharts.CoordinateChart.CheckMinMaxValue () (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:862)
XCharts.CoordinateChart.Update () (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:44)
 
4. NullReferenceException: Object reference not set to an instance of an object
XCharts.CoordinateChart.DrawXAxisSplit (UnityEngine.UI.VertexHelper vh, System.Int32 xAxisIndex, XCharts.XAxis xAxis) (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:1138)
XCharts.CoordinateChart.DrawCoordinate (UnityEngine.UI.VertexHelper vh) (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:974)
XCharts.CoordinateChart.DrawPainterBase (UnityEngine.UI.VertexHelper vh) (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:89)
XCharts.BaseChart.OnDrawPainterBase (UnityEngine.UI.VertexHelper vh, XCharts.Painter painter) (at Assets/XCharts/Runtime/Internal/BaseChart.cs:826)
XCharts.Painter.OnPopulateMesh (UnityEngine.UI.VertexHelper vh) (at Assets/XCharts/Runtime/Internal/Painter.cs:75)
UnityEngine.UI.Graphic.OnPopulateMesh (UnityEngine.Mesh m) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:649)
UnityEngine.UI.Graphic.DoLegacyMeshGeneration () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:600)
UnityEngine.UI.Graphic.UpdateGeometry () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:571)
UnityEngine.UI.Graphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:534)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/CanvasUpdateRegistry.cs:198)
UnityEngine.Canvas:SendWillRenderCanvases() (at C:/buildslave/unity/build/Runtime/UI/ScriptBindings/UICanvas.bindings.cs:72)

5. NullReferenceException: Object reference not set to an instance of an object
XCharts.CoordinateChart.UpdateAxisMinMaxValue (System.Int32 axisIndex, XCharts.Axis axis, System.Boolean updateChart) (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:898)
XCharts.CoordinateChart.CheckMinMaxValue () (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:862)
XCharts.CoordinateChart.InitComponent () (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:34)
XCharts.BaseGraph.Update () (at Assets/XCharts/Runtime/Internal/BaseGraph.cs:98)
XCharts.BaseChart.Update () (at Assets/XCharts/Runtime/Internal/BaseChart.cs:150)
XCharts.CoordinateChart.Update () (at Assets/XCharts/Runtime/Internal/CoordinateChart.cs:48)

**Comment by monitor1394** [comment]
What version of xChart and Unity are you using? 
Can you describe the steps to reproduce the problem?

**Comment by becker88** [comment]
XChart version : 2.1.1-20210413
Unity Version: Unity 2018.4.28f1 (64-bit)
While I run this section the error is produced...
 void Awake()
        {
            var lineChart = gameObject.GetComponent<LineChart>();
            if (lineChart == null)
            {
                lineChart = gameObject.AddComponent<LineChart>();
            }
            lineChart.RemoveData();
            lineChart.AddSerie(SerieType.Line);
            for (int i = 0; i < 10; i++)
            {
                lineChart.AddXAxisData("x" + i);
                lineChart.AddData(0, Random.Range(10, 20));
            }

        }

**Comment by becker88** [comment]
Kindly help me...I am in trouble to implement your xchart....btw your x-chart library is seriously awesome....Great

**Comment by monitor1394** [comment]
I see the cause of your problem. 
Do you want to add a Chart at runtime? This is a bit of a bug, you can add a Chart to Prefab in advance, and then use the script to control it.
I will also try to fix this and make it possible to create charts at runtime.

**Comment by becker88** [comment]
Well, I add chart from Right Click on Canvas and select Xchart and then Line-Chart. If I add data point form LineChart Script ->Series ->Series 0 -> Data (Manually Input)....and Run the Chart it animated and draw the fine file without any error. But while I dynamically input data from my data series though code then Null Ref Exception is occur....one more thing that I can't scroll to view others data...which cut from scene or graph....If you have any old bug free line chart can you please send me the package....
matrix.spbecker@gmail.com (If possible).
![Screenshot 2021-04-26 164208](https://user-images.githubusercontent.com/19772109/116074532-85d8d600-a6af-11eb-9cc0-665677010d52.png)

**Comment by monitor1394** [comment]
I just fixed these exceptions on the master branch.

**Comment by becker88** [comment]
Excellent.....Mind-blowing.....Solution....
Is there any option to live data plot....?

**Comment by monitor1394** [comment]
What are your specific needs?

**Comment by becker88** [comment]
1.There is some stock data  fetch form server...for a specific time interval and display it on graph...that's why I ask you
![Screenshot 2021-04-26 201649](https://user-images.githubusercontent.com/19772109/116103672-710b3b00-a6cd-11eb-9bfb-80b432e048d7.png)

2.One more thing that I can't find ....How can I formatting the Y Axis Level Value....Actually I have fetch some 1000,5000,8000,9000,15000 value I want to format it into 1k, 5k, 8k by dividing 1000 only....How can I do that.

**Comment by monitor1394** [comment]
1. LineChart does not support Time axis yet, you can convert Time to string Category, but the Category is required to be average, and the data can be supplemented by 0.
2. It is not supported yet. Currently, there is only limited support by AxisLabel Formatter and NumericFormatter.
