### ISSUE TITLE
Zoom issue with axis label

### ISSUE THREAD

**Issue by JimZeeKing** [monitor1394/unity-ugui-XCharts#138]
Hi there, first of all, thank you for this neat library! I tried a lot of them and yours is the best one i found.

I have a trouble with zooming and the x axis label being misplaced in relation to the lines in the chart as you can see here : 
![4XJJCnY7Sl](https://user-images.githubusercontent.com/19315887/116099596-1e546380-a67a-11eb-8419-57de0c2a79ff.gif)

Do you know what could cause this behaviour?

**Comment by monitor1394** [comment]
> Hi there, first of all, thank you for this neat library! I tried a lot of them and yours is the best one i found.
> 
> I have a trouble with zooming and the x axis label being misplaced in relation to the lines in the chart as you can see here :
> ![4XJJCnY7Sl](https://user-images.githubusercontent.com/19315887/116099596-1e546380-a67a-11eb-8419-57de0c2a79ff.gif)
> 
> Do you know what could cause this behaviour?

Can you show me the code snippets for clicking the plus and minus buttons?

**Comment by JimZeeKing** [comment]
![image](https://user-images.githubusercontent.com/19315887/116183152-66f83500-a6eb-11eb-82bf-ad940094b9ba.png)

It was my first test. 

Without using code to zoom i have a kind of similar problem, see gif above

**Comment by JimZeeKing** [comment]
Hello again, i tested again this morning but with a really simple line chart (default one, except for some minors changes shown below)

Maybe it can help you find what is going on. Maybe i am not using it correctly?



![image](https://user-images.githubusercontent.com/19315887/116292971-53d57b80-a764-11eb-854a-e369f37fcc54.png)
![image](https://user-images.githubusercontent.com/19315887/116293016-60f26a80-a764-11eb-8b88-92e9c5b91880.png)
![image](https://user-images.githubusercontent.com/19315887/116293070-710a4a00-a764-11eb-9595-d70f90af6464.png)
 And you can see here two things mainly : 

1. 4 data can be shown at once but without x labels being realigned correctly (so its messes with the reading of the data since we cannot use labels space/ticks to read data)
2. A label can be seen outside of the graph area (minor)

![lKgYwZHKEq](https://user-images.githubusercontent.com/19315887/116293455-ea09a180-a764-11eb-9f0f-a6a7dc8e4ad5.gif)

If you need more information, don't hesitate!

Cheers!

**Comment by monitor1394** [comment]
Thank you very much for your feedback. I have fixed the problem on the master branch.
Feel free to give feedback if you have any questions.

**Comment by JimZeeKing** [comment]
Ok, great! Ill try to implement your fix since i can't use the latest version yet (see issue #125 )

**Comment by JimZeeKing** [comment]
Well i implemented your changes in v2.0 and it works now! Thank you.

If i had a suggestion, i would make it so that minShowNum is more of showNum where it's locked at this value and will not show more thant this value (i my case above, it would always show 10 data and never 11. Either way, thank you for your answers!
