### ISSUE TITLE
RadarChart Issue: Cannot switch to Circle Shape

### ISSUE THREAD

**Issue by nixcry** [monitor1394/unity-ugui-XCharts#139]
Trigger the issue:
Create a RadarChart, change [Radar 0 ->Shape] from "Polygon" to "Circle". 
The expected effect won't happen and the following error occurs:
DivideByZeroException: Attempted to divide by zero.
  at XCharts.DrawSerieRadar.DrawCricleRadar (UnityEngine.UI.VertexHelper vh, XCharts.Radar radar) [0x000b1] in D:\SmartRepo\Assets\XCharts\Runtime\Internal\DrawSerieRadar.cs:693 

Bypass the issue:
Set [ Radar 0 ->Split Area -> Color -> Size ] to something other than"0" before switching the Shape to Circle.

I think this is a bug.
![image](https://user-images.githubusercontent.com/45841722/116529031-119c6d80-a90f-11eb-9bcb-33473cca1f3f.png)

**Comment by monitor1394** [comment]
Thanks for the feedback. It has been fixed in master branch.
