### ISSUE TITLE
什么时候 使用 AssemblyDefinition 并持PackageManager 

### ISSUE THREAD

**Issue by Bian-Sh** [monitor1394/unity-ugui-XCharts#14]
我使用昨天（1018）更新的版本整理的 AssemblyDefinition 支持和 PackageManager 支持
可以下载下来参考或者直接使用。

使用方法：
菜单栏 - Windows - PackageManager - 点击加号 - 弹出窗口选择 - XCharts文件夹下的Package.json

下载链接：
链接：https://pan.baidu.com/s/1k3FXWTr6yJrmCcgLffYseg&shfl=sharepset 
提取码：eouh

**Comment by Bian-Sh** [comment]
> 我使用昨天（1018）更新的版本整理的 AssemblyDefinition 支持和 PackageManager 支持
> 可以下载下来参考或者直接使用。
> 
> 使用方法：
> 菜单栏 - Windows - PackageManager - 点击加号 - 弹出窗口选择 - XCharts文件夹下的Package.json
> 
> 下载链接：
> 链接：https://pan.baidu.com/s/1k3FXWTr6yJrmCcgLffYseg&shfl=sharepset
> 提取码：eouh

可以参考这个工作流开发和发布UPM 包
https://www.patreon.com/posts/25070968

**Comment by monitor1394** [comment]
非常感谢！我会尽快整理支持。

**Comment by monitor1394** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/1450329/67170131-48242e80-f3e2-11e9-8114-fc057d108a71.png">
分了AssemblyDefinition后Editor的识别不了Runtime里的类了，还需要其他设置吗

**Comment by monitor1394** [comment]
忘记设置饮用了
