### ISSUE TITLE
Custom Shader or Material

### ISSUE THREAD

**Issue by nixcry** [monitor1394/unity-ugui-XCharts#140]
Hi!
Is there any way to replace the attached "Default UI Material" with a custom one?
If not, would you consider adding an exposed "Material" property somewhere on the editor GUI in a future version, just like the built-in Text Element?
![image](https://user-images.githubusercontent.com/45841722/116667251-8f737e00-a9ce-11eb-8e5a-1e5d0edbc975.png)

**Comment by monitor1394** [comment]
It is supported on the master branch.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/1450329/116786030-50792180-aacf-11eb-8990-ed0b22f5a7b9.png">
or：
<img width="700" alt="image" src="https://user-images.githubusercontent.com/1450329/116786058-6be42c80-aacf-11eb-8b31-59d5892c869d.png">
