### ISSUE TITLE
有没有类似echarts的Markline

### ISSUE THREAD

**Issue by TotalVisit** [monitor1394/unity-ugui-XCharts#142]
请问有没有类似echarts的Markline配置，超出某个值，超出部分显示红色或其他颜色

**Comment by monitor1394** [comment]
暂不支持。

**Comment by monitor1394** [comment]
预计v2.3.0版本会支持（6月）

**Comment by monitor1394** [comment]
MarkLine最新的master已支持。但
> 超出某个值，超出部分显示红色或其他颜色

这个不是MarkLine的功能，可用VisualMap来实现。

**Comment by monitor1394** [comment]
release版 v2.3.0 已支持。
