### ISSUE TITLE
TMP font asset variable missing from theme when tmp is enabled

### ISSUE THREAD

**Issue by Reddevildragg** [monitor1394/unity-ugui-XCharts#143]
Hi

current in the inspector when enableing tmp, many of the fields update to show the tmp_font field and not unitys standard font field. This is not the case for the main theme asset and stays as the tmp_font, I can tun the inspector mode into debug mode and set it, but just a heads up. Image below to help show what i mean

![image](https://user-images.githubusercontent.com/19800074/117651640-14f2ed00-b18a-11eb-885f-f3ece7c092fa.png)

**Comment by Reddevildragg** [comment]
Brillinat thanks, ill check out the master branch version and all should be good then. Thanks for quick response

**Comment by monitor1394** [comment]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/1450329/117822742-6345e000-b29f-11eb-948a-8da551cbf5a4.png">
You can also set it globally in XChartSettings, which eliminates the need for each Chart Theme to be set separately.
