### ISSUE TITLE
时间类型的横轴(X轴)如何对应数据 | How to fit serie data when X Axis type is TIME

### ISSUE THREAD

**Issue by ningyuv** [monitor1394/unity-ugui-XCharts#144]
# 版本 | Version
v2.1.1 XCharts-2.1.1.unitypackage
# 需求 | Expectations
在Echarts中有[此例](https://echarts.apache.org/examples/en/editor.html?c=area-time-axis)可以在X轴为时间时，指定SeriaData的X值。
Here is a [example](https://echarts.apache.org/examples/en/editor.html?c=area-time-axis) in Echarts. When xAxis.type is 'time', it can specify data.x
例如： | Code Example:
```js
{
    ...,
    xAxis: {
        type: 'time',
        ...
    },
    yAxis: {
        type: 'value',
        ...
    },
    series: [
        {
            ...,
            data: [
                ['1970/1/1', 1],
                ['1970/1/2', 2],
                ['1970/1/5', 3]
            ]
        }
    ]
}
```
# 发现 | Discovery
该项目的SeriaData全部为`float`类型，文档中也没有指定时间的例子。
In this project `Serie.data` is a [`List<SerieData>`](https://github.com/monitor1394/unity-ugui-XCharts/blob/c1f604f1b6f77c1637501b9f7a39a6a4cce6e9f9/Assets/XCharts/Runtime/Component/Main/Serie.cs#L937) and `SerieData.data` is a [`List<float>`](https://github.com/monitor1394/unity-ugui-XCharts/blob/c1f604f1b6f77c1637501b9f7a39a6a4cce6e9f9/Assets/XCharts/Runtime/Component/Sub/SerieData.cs#L109). So it seems cannot set SerieData a time string(`1970/1/1`).
# 问题 | Question
如何达到上述Echarts中的效果，或者说当X轴为时间时，如何指定SerieData的X值？
How to achieve the above effect like Echarts.

**Comment by monitor1394** [comment]
暂时还不支持时间轴。

**Comment by monitor1394** [comment]
先自己格式化转为字符串，用类目轴吧
