### ISSUE TITLE
希望对AxisLabel增加基于代码的formatter | need a scriptable formatter for AxisLabel

### ISSUE THREAD

**Issue by ningyuv** [monitor1394/unity-ugui-XCharts#145]
# 版本 | Version
v2.1.1
# 需求 | Expectations
需要一个能够用代码控制的formatter来自定义[AxisLabel](https://github.com/monitor1394/unity-ugui-XCharts/blob/c1f604f1b6f77c1637501b9f7a39a6a4cce6e9f9/Assets/XCharts/Runtime/Component/Sub/AxisLabel.cs)
need a scriptable formatter for [AxisLabel](https://github.com/monitor1394/unity-ugui-XCharts/blob/c1f604f1b6f77c1637501b9f7a39a6a4cce6e9f9/Assets/XCharts/Runtime/Component/Sub/AxisLabel.cs)
# 发现 | Discovery
当前有2个formatter，都是字符串形式
Here are 2 `formatter`s with string type.

- [formatter](https://github.com/monitor1394/unity-ugui-XCharts/blob/c1f604f1b6f77c1637501b9f7a39a6a4cce6e9f9/Assets/XCharts/Runtime/Component/Sub/AxisLabel.cs#L72)
- [numericFormatter](https://github.com/monitor1394/unity-ugui-XCharts/blob/c1f604f1b6f77c1637501b9f7a39a6a4cce6e9f9/Assets/XCharts/Runtime/Component/Sub/AxisLabel.cs#L85)

只能设置字符串而不能通过代码进行自定义
或许可以增加一个formatter，类型为函数或Lambda
Could we need a scriptable formatter?

**Comment by Bian-Sh** [comment]
可以开放接口，数据源所在的类继承它，即可自定义指定数据的format了
```
namespace XCharts.Examples
{
    // interface for end_user to change tips  
    public interface ITooltipsFormatHandler
    {
        string OnToolTipsDisplayed(int index);
    }
   // this class shows us how can we define custom tips by this interface
    public class Foo : MonoBehaviour, ITooltipsFormatHandler
    {
        private int[] data_x = new int[] { 1, 2, 3 };
        private LineChart chart;
        private void Start()
        {
            chart.tooltipsFormatHandler = this;
        }

        public string OnToolTipsDisplayed(int index)
        {
            return $"{data_x[index]} KM\tSomeOtherCustomInformation";
        }
    }
    // This is fake type show how interface be called inside of a chart.
    public class LineChart : MonoBehaviour
    {
        public ITooltipsFormatHandler tooltipsFormatHandler;
        public int index; //current serie index
        public void ShowTips()
        {
            if (null != tooltipsFormatHandler)
            {
                var tip = tooltipsFormatHandler.OnToolTipsDisplayed(index);
            }
            else
            {
                //xchart default format 
            }
        }
    }
}
```

**Comment by monitor1394** [comment]
预计v2.3.0版本会支持（6月）

**Comment by monitor1394** [comment]
最新的master分支已支持通过实现AxisLabel和SerieLabel的formatter委托方法来自定义文本显示。
