### ISSUE TITLE
Add Serie 窗口录入的 Serie name 无法写入到图表配置中

### ISSUE THREAD

**Issue by Bian-Sh** [monitor1394/unity-ugui-XCharts#149]
![image](https://user-images.githubusercontent.com/24520547/119172237-462bc100-ba98-11eb-8691-7d6493079640.png)

问题：
 在 serie name 中录入中文并点击 ADD，发现 图表series中新增一个系列，但是serie name 依旧是 默认的 serie7
Unity 版本：
Unity 2019.4.13f1

**Comment by monitor1394** [comment]
master已修复。
