### ISSUE TITLE
刚运行的时候x轴的数据会有重叠怎么修改

### ISSUE THREAD

**Issue by lhao407** [monitor1394/unity-ugui-XCharts#15]
x轴设置为类目轴，设置了五个分割段数，运行后x轴从0增加到10，然后才变成5，怎么设置可以从0增加到5就不增加了。谢谢

**Comment by monitor1394** [comment]
splitNumber一般用在数值轴中，在类目轴中的主要还是依据里面的data进行分割，当data的size是splitNumber两倍以上时才会生效。要不然没法很好的展示数据。

**Comment by lhao407** [comment]
好的谢谢
