### ISSUE TITLE
一些textStyle.alignment设置似乎没有生效

### ISSUE THREAD

**Issue by yu-xiaowen** [monitor1394/unity-ugui-XCharts#150]
我使用的是 2.1.1版
`
using UnityEngine;
using XCharts;

public class TestAlignment : MonoBehaviour
{
    public PieChart aPieChart;

    void Start()
    {
        initAPieChart();
    }

    void initAPieChart()
    {
        aPieChart.ClearData();
        aPieChart.AddData(0, 105, "数据1");
        aPieChart.AddData(0, 132, "数据2");
        aPieChart.AddData(0, 116, "数据3");
        aPieChart.AddData(0, 94, "数据4");
        aPieChart.AddData(0, 121, "数据5");
        aPieChart.AddData(0, 52, "数据6");
        aPieChart.AddData(0, 189, "数据7");

        aPieChart.rectTransform.sizeDelta = new Vector2(1200, 800);

        aPieChart.series.GetSerie(0).label.show = true;
        aPieChart.series.GetSerie(0).label.line = true;
        aPieChart.series.GetSerie(0).label.lineLength1 = 50;
        aPieChart.series.GetSerie(0).label.textStyle.alignment = TextAnchor.MiddleLeft;
        aPieChart.series.GetSerie(0).label.formatter = "{b}{b}\n{c}";
        aPieChart.series.GetSerie(0).radius = new float[2] { 0f, 200f };
    }
}
`

`aPieChart.series.GetSerie(0).label.textStyle.alignment = TextAnchor.MiddleLeft; `
这句设置了左对齐，文字分两行显示，但是依然是居中显示的。

另外设置柱状图的横轴标签文字的对齐方式也看不到效果： 
`aBarChart.xAxis0.axisLabel.textStyle.alignment = TextAnchor.MiddleRight; `
这样设置后，我预期的是一段文字右侧和柱的中心线对齐，但是看到的仍然是一段文字中间和柱的中心线对齐。

谢谢作者开发的图表程序。

**Comment by monitor1394** [comment]
master已支持。Release要晚几天再发。
要用textStyle的设置的对齐需要设置autoAlign为true。
