### ISSUE TITLE
diffrent color in editor ok but in code not work.

### ISSUE THREAD

**Issue by shriffadl** [monitor1394/unity-ugui-XCharts#151]
i try candle stick chart ,i add two data by editor easy ,i change the color for every data easy
under candlesticchart---series---data---
i press more so i see under emement0 and element1 some parameters,
i checked itemstyle enabled., i choose the color.for element0
i checked itemstyle enabled., i choose the diffrent color .for element1
its worket ok.

i try to do the same from code .but i cannt access the data ,or if acces the data i cannt find itemstyle.

**Comment by monitor1394** [comment]
First, get the SerieData:
```C#            
var serieData = chart.AddData(0, 100);
// or
var serieData = chart.series.GetSerie(0).GetSerieData(0); 
```

Then, modify the SerieData:

```C#            
serieData.enableItemStyle = true;
serieData.itemStyle.color = Color.red;
```

**Comment by shriffadl** [comment]
thank you its working.

this is your code and it work for me.
                           var serieData = Chart1.series.GetSerie(0).GetSerieData(0);
                            serieData.enableItemStyle = true;
                            serieData.itemStyle.color = Color.red;
                            serieData.itemStyle.borderColor = Color.yellow;
                            serieData.itemStyle.borderColor0 = Color.yellow;

this is my 1st code not work.
                            Series m_Series = Series.defaultSeries;
                            Serie serie = m_Series.GetSerie("serie1");
                            serie.GetSerieData(j).enableItemStyle = true;
                            serie.GetSerieData(j).itemStyle.borderColor = Color.white;
                            serie.GetSerieData(j).itemStyle.borderColor = Color.white;

this is my 2nd code not work.
                            DataZoom dataZoom = Chart1.dataZoom;
                            Series m_Series = Series.defaultSeries;
                            Serie serie = m_Series.GetSerie("serie1");
                            var showData = serie.GetDataList(dataZoom);
                            var serieData = showData[j];
                            serieData.enableItemStyle = true;
                            serieData.itemStyle.borderColor = Color.yellow;
                            serieData.itemStyle.borderColor0 = Color.yellow;

**Comment by monitor1394** [comment]
It doesn't make sense：
`Series m_Series = Series.defaultSeries;`

You must get it from chart：
`var series = chart.series;`

**Comment by shriffadl** [comment]
sure , thank you
please add one example in the examples folder ,
and name it as "different color for specific point by code. and add this example.
