### ISSUE TITLE
如何实现图示中的2维柱图数据的图表

### ISSUE THREAD

**Issue by whowatchoverwatch** [monitor1394/unity-ugui-XCharts#155]
![3维数据](https://tva1.sinaimg.cn/large/008i3skNgy1grbt2n80jgj30hu0a6tct.jpg)
如图所示，如何实现上图中的图表
无法更改一个series内柱体之间的距离
我现在能做到的为

![现况](https://tva1.sinaimg.cn/large/008i3skNgy1grbt2kb53nj30f408ymya.jpg)

**Comment by monitor1394** [comment]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/1450329/121444822-c8861180-c9c2-11eb-913a-2c333e7e271c.png">
XAxis两个数据 2018，2019
4个serie，每个serie两个数据，可以调barWidth和barGap调整主题宽度和间距
