### ISSUE TITLE
大佬们，如何更改表格的边距？

### ISSUE THREAD

**Issue by Sun-FreePort** [monitor1394/unity-ugui-XCharts#156]
![03](https://user-images.githubusercontent.com/19473984/122237419-e3d8ab80-cef1-11eb-9ecd-81f07e0a4305.png)

 见图，这个表格间距有点大

竖屏嘛，48个值连起来又有点小，想把边距吃掉！

**Comment by monitor1394** [comment]
调Grid下的参数

**Comment by Sun-FreePort** [comment]
大佬厉害！爱了爱了
