### ISSUE TITLE
左边Y轴数据不同步  值太小了  麻烦大佬瞅一下

### ISSUE THREAD

**Issue by zhaohuaican** [monitor1394/unity-ugui-XCharts#16]
![$ EB{)U(PNDFV 80HGQF8SO](https://user-images.githubusercontent.com/56996817/67557092-f9122c80-f746-11e9-87fa-5448c90d9d65.png)

**Comment by monitor1394** [comment]
1.0.1版本已修复。

1. 增加科学计数法显示数值的支持（查阅`forceENotation`参数）
2. 增加`Axis`类目轴数据为空时的默认显示支持
3. 增加`Axis`数值轴的最大最小值可设置为小数的支持，优化极小数图表的表现效果
