### ISSUE TITLE
Does not work with MRTK ponters

### ISSUE THREAD

**Issue by studentutu** [monitor1394/unity-ugui-XCharts#162]
Please, try import and test the MRTK package from Microsoft. It does support all of the native event triggers, but the current implementation of the check is inside chart starts from the center, while the event data comes from the MRTK Event System and it counts from the left lower corner, thus creating a block for pointers. 

Thank you!

**Comment by monitor1394** [comment]
Thanks for the feedback.
But I think you may need to change the source code by yourself, because I may not be able to deal with this problem that quickly.

If you have any good idea, welcome feedback or  PR.

**Comment by studentutu** [comment]
yes, resolved it by adding additional method that checks if the MRTK is present, and if so check the correct corners (same method in Xchart checks 2 methods)
