### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by unbounded26** [monitor1394/unity-ugui-XCharts#164]
1. UI - Sometimes x-axis label doesn't update its style i.e. rotation, offset, margin.

2. Data Points - What's the limitation of the values in the graph in given rect, as I tried to show the data points for 1 year, it worked. But when I tried to show the values of 2 years, it didn't worked.
As I can skip some values in x-axis label, so the x-axis label will not overlap.

3. Data Points - Line graph, if the value is 0 it is set as skip, then in Line graph, it should show a disconnected line. Or at least you can give a check mark to show disconnected line or not.
As in shared example, there should be 4 disconnected lines (2 green, 2 orange)
<img width="258" alt="Screenshot 2021-08-18 at 4 51 00 PM" src="https://user-images.githubusercontent.com/7029364/129869873-490fb99d-c224-4acb-950d-9c173477f83d.png">

4. Kindly provide the event when a tooltip is shown on a specific point with the separate data (points values and x-axis label) on that point. It will be very helpful in many data points to perform some tasks

**Comment by monitor1394** [comment]
1. I may need some time to test and fix this, but you can manually refresh Axis with the code first: 
    `xAxis.SetAllDirty();`
2. Are there any related errors or exceptions？Such as, `Mesh can not have more than 65000 vertices`. AxisLabel's `interval` can skip label.
3. You can use `VisualMap` instead for the time being. But it may not be a good idea when there is a lot of data.
4. Very useful advice.

By the way, I'm currently fully working on version 3.0, so some of the more complex requirements may be put on hold or implemented together with version 3.0.
But if a feature is important to you, please let me know, and I'll manage my time to support it.

**Comment by unbounded26** [comment]
> 1. I may need some time to test and fix this, but you can manually refresh Axis with the code first:
>    `xAxis.SetAllDirty();`

This didn't work, more details are in [this](https://github.com/monitor1394/unity-ugui-XCharts/issues/163) thread.
> 2. Are there any related errors or exceptions？Such as, `Mesh can not have more than 65000 vertices`. AxisLabel's `interval` can skip label.

No, I don't get this error
> 3. You can use `VisualMap` instead for the time being. But it may not be a good idea when there is a lot of data.

Still, it makes sense in a line graph. It will be disconnected lines and dots (I mean where the data is continuous the line continues till that where the value is 0, the line ends. And again starts from the next sequence of data)
> 4. Very useful advice.
> 
Thanks!
> By the way, I'm currently fully working on version 3.0, so some of the more complex requirements may be put on hold or implemented together with version 3.0.
> But if a feature is important to you, please let me know, and I'll manage my time to support it.

May I know when version 3.0 is ready to use? Very excited about that, as it is a very useful graph plugin.

Issue 1 and 3 is very important for now, especially issue 1

**Comment by monitor1394** [comment]
> Issue 1 and 3 is very important for now, especially issue 1

I have fixed Issue1 and 3 in 2.0 branch.

> May I know when version 3.0 is ready to use? Very excited about that, as it is a very useful graph plugin.

Version 3.0 will not be released until September at the earliest. Version 3.0 change a lot and there is a lot of work to do.
