### ISSUE TITLE
2.0柱状图疑问

### ISSUE THREAD

**Issue by zerofourfive** [monitor1394/unity-ugui-XCharts#175]
柱状图的Series里Label的Formatter  {}里是大小写通用的吗？   {a} {d}  功能正常  {c}只有大写能用  小写的用不了  {b}大小写都用不了 
![111](https://user-images.githubusercontent.com/35764286/144534608-912b5f0f-b928-424f-8502-3f209c3cc2f6.png)
![222](https://user-images.githubusercontent.com/35764286/144534622-34d4c0e1-dabf-47ba-9480-ab930aab4ca4.png)

**Comment by monitor1394** [comment]
2.0分支已修复
