### ISSUE TITLE
折线图显示SplitLine左侧多出一列

### ISSUE THREAD

**Issue by TiaJC** [monitor1394/unity-ugui-XCharts#181]
折线图：设置了AlignWithLabel后，显示SplitLine会有一个在左侧不对的偏移
![QQ图片20220214165026](https://user-images.githubusercontent.com/26160033/153830656-62faf10c-9f91-4c95-87a0-cdb87e600345.png)
![QQ图片20220214165030](https://user-images.githubusercontent.com/26160033/153830664-c6a59c95-7c2d-48ae-ae63-30df4048c54b.png)

**Comment by monitor1394** [comment]
2.0分支上已修复
