### ISSUE TITLE
When building, "A chart named 'chart name' already exists

### ISSUE THREAD

**Issue by Tom4259** [monitor1394/unity-ugui-XCharts#183]
When building for android, i get two errors which are the exact same:

` A chart named 'Steps this week vs last week' already exists:Canvas/MainScreen/Screens/Analytics screen/Graphs/stats/Viewport/Content/LineChart
UnityEngine.Debug:LogError (object)
XCharts.XChartsMgr:AddChart (XCharts.BaseChart) (at Assets/XCharts/Runtime/XChartsMgr.cs:265)
XCharts.BaseChart:Awake () (at Assets/XCharts/Runtime/Internal/BaseChart.cs:125)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

How do i fix this?

**Comment by monitor1394** [comment]
Do you set chartName? 
If you set chartName, make sure it's unique.
<img width="449" alt="image" src="https://user-images.githubusercontent.com/1450329/154379409-4aec6cb9-dc5b-4268-b2db-420ed92bf885.png">

**Comment by Tom4259** [comment]
I have just been testing, and i have 2 graphs with each different names, even if i create a new graph and set the name to anything, then the warning will show, if i leave the name blank, then there is no error. Thanks for your response.

**Comment by monitor1394** [comment]
Which XCharts version are you using?
I checked the latest code and felt that this exception would not happen, But I've added judgment protection.

**Comment by Tom4259** [comment]
![image](https://user-images.githubusercontent.com/63543782/154382173-bdee1b81-f193-43dd-8116-923779e6449f.png)

I have done some more testing and i have solved a few thoughts i had. I restarted the Unity Editor and checked for warning, result was 'Perfect' on both my graphs, duplicated ONE of the graphs and checked the warning on BOTH graphs which gave the 'Already exists' warning. I think this should help.

**Comment by Bian-Sh** [comment]
在图表被克隆时，应该自动输出提示：“图表名称冲突，请确认新增图表的名称。”

**Comment by Tom4259** [comment]
Yes, but after that, i immediately change the name of the chart. I then press the check warning and it tells me that the chart name '[chart name]' is repeated, but it isn't.

**Comment by monitor1394** [comment]
> 

I have fixed it in 2.0 branch.
