### ISSUE TITLE
能增加一个圆角的效果吗

### ISSUE THREAD

**Issue by shenhuilin** [monitor1394/unity-ugui-XCharts#21]
![ZY8EB}Y7ZW8XTI5B1@VMN@7](https://user-images.githubusercontent.com/31879581/68557266-434a1c00-0470-11ea-84b6-ef0b67e72098.png)
把这种直角
![_4}IW5_BSY B)4{{WU5OUU](https://user-images.githubusercontent.com/31879581/68557304-62e14480-0470-11ea-97bc-03714a5478d3.png)
改成圆角

**Comment by monitor1394** [comment]
(2019.12.03)更新已支持环形饼图的圆角效果。
参数：serie.arcShaped
