### ISSUE TITLE
BarChart修改data后导致lable不能正确显示

### ISSUE THREAD

**Issue by lcchenlin** [monitor1394/unity-ugui-XCharts#24]
BarChart设置了Data，把Size改为0又重新改为5，然后填上数据，label消失。重启也设置不了。
![image](https://user-images.githubusercontent.com/36942684/69392024-92653c00-0d0f-11ea-97c9-e71cc6bf0a0f.png)

**Comment by monitor1394** [comment]
已修复。
(2019.11.22) 修复BarChart清空数据重新赋值后SerieLabel显示异常的问题
