### ISSUE TITLE
增加适配分屏后事件响应

### ISSUE THREAD

**Issue by ydx1987** [monitor1394/unity-ugui-XCharts#25]
当前现象：在分屏AB屏时，鼠标在A屏操作时，B屏里的xcharts会响应到鼠标事件。鼠标移到B屏时反而没有事件响应了，UGUI的组件都正常响应。
实现逻辑：有2个canvas和2个camera，2个camera分别对应A屏的display1和B屏的display2。
临时解决方案：A屏显示原本B屏的内容，B屏显示原本A屏的内容。
ps：目前定位在BaseChart.cs里CheckPointerPos()方法中，希望在以后的版本支持本提案。
谢谢提供帮助！

**Comment by monitor1394** [comment]
感谢反馈。我会尽快修复这个问题。

**Comment by monitor1394** [comment]
(2019.12.16)的更新已修复这个问题。
