### ISSUE TITLE
设置xAxises的MaxCache之后显示错误，数据对不上

### ISSUE THREAD

**Issue by CYBoys** [monitor1394/unity-ugui-XCharts#26]
￼￼￼￼￼
![image](https://user-images.githubusercontent.com/15981638/69911900-1da3a780-145d-11ea-9fd5-24d49ec152dd.png)

**Comment by monitor1394** [comment]
serie也要对于的设置maxCache

**Comment by CYBoys** [comment]
请问可以添加数据之后的移动动画吗？

**Comment by monitor1394** [comment]
移动动画目前暂不支持。
