### ISSUE TITLE
label名称太长设置省略模式

### ISSUE THREAD

**Issue by lcchenlin** [monitor1394/unity-ugui-XCharts#27]
设置省略模式，坐标轴名称过长自动省略显示省略号。最好能弹tips显示全名。

**Comment by monitor1394** [comment]
> * (2020.01.26) 增加`TextLimit`组件可以设置`AxisLabel`的文本自适应

1.26更新已支持设置类目轴文本自适应。暂不支持文本弹tips显示全面（tooltip本身可以显示全名了）
