### ISSUE TITLE
数据超出无隐藏功能（新增属性）

### ISSUE THREAD

**Issue by binghuangddn** [monitor1394/unity-ugui-XCharts#28]
图表固定了y的值，数据超出之后没有隐藏的功能，影响美观，希望增加一个是否隐藏超出数据的属性

**Comment by monitor1394** [comment]
> * (2020.02.10) 增加`Serie`的`clip`参数控制是否超出坐标系外裁剪（只适用于折线图、柱状图、散点图）

2020.02.10更新已支持超出部分裁剪功能（设置serie的clip参数）
