### ISSUE TITLE
柱状图y轴刻度无法整数

### ISSUE THREAD

**Issue by zhangxinwu112** [monitor1394/unity-ugui-XCharts#39]
barChart.yAxis0.axisLabel.formatter = "{value:f0}"，无法完全显示整数数值。

**Comment by monitor1394** [comment]
> (2020.01.15) 增加`AxisLabel`格式化为整数的支持（`{value:f0}`）

已支持格式化为整数：AxisLabel的formatter设置为{value:f0}
