### ISSUE TITLE
根据鼠标位置绘制的线不会删除

### ISSUE THREAD

**Issue by StudentYan-Ling** [monitor1394/unity-ugui-XCharts#4]
首先感谢您的贡献，我在使用的时候发现了一点小问题，
![image](https://user-images.githubusercontent.com/34509356/58699684-a408ff00-83d0-11e9-9361-eda018bffcc9.png)
这种线似乎在鼠标移动出图表之后并没有消失

**Comment by monitor1394** [comment]
嗯，鼠标移出太快时可能会触发这个问题，晚点我修复一下

**Comment by monitor1394** [comment]
我多次测试是没发现指示线不会消失的问题，倒是Tooltip是有可能不会消失，这个问题已经处理了。你可以更新最新代码看看还有没有这个问题。

**Comment by StudentYan-Ling** [comment]
我更新了最新代码，还是有这个问题，跟版本会有关系吗 我是2017.4

**Comment by monitor1394** [comment]
具体哪个版本，我测试下

**Comment by StudentYan-Ling** [comment]
我是2017.4.3f1，
我刚才看了一下代码，在BaseChart类里CheckTooltip方法里第334行和340行的return之前调用了一次RefreshChart，解决了这个问题，这是正确的解决方法吗？

**Comment by monitor1394** [comment]
是的

**Comment by StudentYan-Ling** [comment]
感谢您的帮助，请您在下次更新修复这个问题吧，这个Issues我就关闭了

**Comment by monitor1394** [comment]
这个问题修复提交了
