### ISSUE TITLE
Any english doc planned?

### ISSUE THREAD

**Issue by adepierre** [monitor1394/unity-ugui-XCharts#43]
Hi!

I just found this tool and I find it amazing, thanks for your work!

Do you have by any chance planned to release an english version of the doc? 

Thanks!

**Comment by monitor1394** [comment]
Hi!
Thanks for your feedback.
Yes,I have planned to release an  english version doc, but it may take one or a few months.
Many APIs are commented in Chinese and English, and I will continue to update.
You can email me if you have any questions.
