### ISSUE TITLE
請問如何添加一筆空資料到折線圖內？

### ISSUE THREAD

**Issue by Jim3878** [monitor1394/unity-ugui-XCharts#44]
我在做一個每日記錄體重的圖表，但使用者不一定會每日登記體重
目前代碼如下
```
 sportChart.AddXAxisData(currDate.ToString("MM/dd"));
            var idx = dataList.FindIndex(x => x.date.ToString("MM/dd") == currDate.ToString("MM/dd"));
            if (idx != -1)
            {
                sportChart.AddData(0, dataList[idx].weight,currDate.ToString("MM/dd"));
                Debug.Log(i);
                
            }
```

但全部的資料都會往前遞補，請問要如何才能將資料添加到指定的日期裡面？

**Comment by monitor1394** [comment]
假设dataList中已存了所有已记录的体重数据，并且都加入到了chart中。
当currDate在dataList时，需要用chart.UpdateData来更新数据，这时不用AddXAxisData（因为chart中已存在了）
```
var dataIndex = dataList.IndexOf(currDate);
chart.UpdateData(0,dataIndex,value);
```
当currDate不在dataList时，一种简单的处理是：将currData加入dataList，然后dataList按时间排序，所有数据重新加入chart中：
```
chart.ClearData();
for(int I=0;i<dataList.Count;i++)
{
    chart.AddXAxisData();
    chart.AddData();
}
```

**Comment by Jim3878** [comment]
謝謝你這麼快就回應我的問題

我剛才試了下UpdateData，但看起來這個method的用途是修改原本在chart中的數值
例如把3/8的體重從55kg改成60kg，不知道我的理解有沒有問題

而我的狀況是，如果日期有10天而使用者在中間4天沒有登錄體重，我目前只能生成下面的圖表
![圖片](https://user-images.githubusercontent.com/26409075/76192361-93699d00-621c-11ea-8187-75c7a90afeac.png)

而我希望能得到下面的圖表
![圖片](https://user-images.githubusercontent.com/26409075/76192518-f3f8da00-621c-11ea-84fa-81d02a2ce073.png)

我試過使用
```SerieData AddData(int serieIndex, float xValue, float yValue, string dataName = null)```
的method加入data，但這種加法卻沒辦法將x軸的值顯示為日期

**Comment by monitor1394** [comment]
我明白你的意思。
目前有在开发这个功能：忽略指定值的数据（默认为0），被忽略的数据不会进行绘制，但x轴会保留。可能需要1-3天才会提交。
这个功能有了之后，没有录入数据的那4天可以默认数据为0。应该就实现了你要的效果。

**Comment by monitor1394** [comment]
> * (2020.03.10) 增加`LineChart`的普通折线图可通过设置`ingore`参数过滤数据的支持

3月10日的更新已支持设置忽略数据，目前只支持普通折线图（其他的待开发）。

**Comment by Jim3878** [comment]
你好，我把新版本的xchart放到專案了，效果十分出色。
但在用隨機數據刷新數據時發現了一些問題，我把資料整理在下面

### 折線圖無法繪製問題

某次隨機產的數據無法正確顯示
![](https://i.imgur.com/XkLiUH1.png)
檢查後發現是因為這組數據最後一筆資料是0的緣故，只要將最後一筆資料改為正數即可顯示
![](https://i.imgur.com/9VXoWIB.png)
但若第一筆資料及最後一筆資料同時都是0時，也是可以正確顯示
![](https://i.imgur.com/B3yPbkt.png)


### 折線圖中斷問題

![](https://i.imgur.com/6RkeQ9u.png)
原因不明確，但好發在兩筆數值差距為10左右且中間夾了至少一筆0資料的情況
![](https://i.imgur.com/mt39hQi.png)

此圖顯示就算同為[69,80,90]的數列也不一定會導致折線圖中斷
![](https://i.imgur.com/LHVcnko.png)

另一筆會導致中斷發生的數據
![](https://i.imgur.com/OKttQ11.png)

**Comment by monitor1394** [comment]
感谢反馈，非常详细！我抽空处理下。

**Comment by monitor1394** [comment]
已发布了v1.3.1版本解决了这些问题。

**Comment by Jim3878** [comment]
感謝，剛剛把新版本的xcharts實裝後完全沒有問題！
再次感謝您的維護及開發
