### ISSUE TITLE
请问如何用代码修改pie模式下element参数呢

### ISSUE THREAD

**Issue by Lixiaojun1234** [monitor1394/unity-ugui-XCharts#47]

**Comment by monitor1394** [comment]
请先下[API手册](https://github.com/monitor1394/unity-ugui-XCharts/blob/master/Assets/XCharts/Documentation/XChartsAPI.md)和[配置项手册](https://github.com/monitor1394/unity-ugui-XCharts/blob/master/Assets/XCharts/Documentation/XCharts配置项手册.md)。

如果只是更新pie的数据，可用UpdateData接口。
