### ISSUE TITLE
关于图标的点击事件

### ISSUE THREAD

**Issue by NianHanDad** [monitor1394/unity-ugui-XCharts#48]
作者可以加点图片的区域对外的鼠标事件嘛 如鼠标进入柱状图某条数据的事件，点击事件，离开事件等。这将是一个非常好用的功能。感谢作者

**Comment by monitor1394** [comment]
已加入开发计划，预计下个版本支持

**Comment by monitor1394** [comment]
目前只支持以下的部分通用鼠标事件，其他的暂不支持了。
* `BaseChart.onPointerClick`：鼠标点击回调。
* `BaseChart.onPointerDown`：鼠标按下回调。
* `BaseChart.onPointerUp`：鼠标弹起回调。
* `BaseChart.onPointerEnter`：鼠标进入图表回调。
* `BaseChart.onPointerExit`：鼠标退出图表回调。
* `BaseChart.onBeginDrag`：鼠标开始拖拽回调。
* `BaseChart.onDrag`：鼠标拖拽回调。
* `BaseChart.onEndDrag`：鼠标结束拖拽回调。
* `BaseChart.onScroll`：鼠标滚动回调。

**Comment by NianHanDad** [comment]
感谢作者&nbsp; 十分感谢！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"monitor1394"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上8:39
收件人:&nbsp;"monitor1394/unity-ugui-XCharts"<unity-ugui-XCharts@noreply.github.com&gt;;
抄送:&nbsp;"✿The  Root 、"<303697518@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [monitor1394/unity-ugui-XCharts] 关于图标的点击事件 (#48)





 
目前只支持以下的部分通用鼠标事件，其他的暂不支持了。
  
BaseChart.onPointerClick：鼠标点击回调。
 
BaseChart.onPointerDown：鼠标按下回调。
 
BaseChart.onPointerUp：鼠标弹起回调。
 
BaseChart.onPointerEnter：鼠标进入图表回调。
 
BaseChart.onPointerExit：鼠标退出图表回调。
 
BaseChart.onBeginDrag：鼠标开始拖拽回调。
 
BaseChart.onDrag：鼠标拖拽回调。
 
BaseChart.onEndDrag：鼠标结束拖拽回调。
 
BaseChart.onScroll：鼠标滚动回调。
