### ISSUE TITLE
背景色更改成透明

### ISSUE THREAD

**Issue by kunlee1105** [monitor1394/unity-ugui-XCharts#49]
背景色只能采用RGB颜色，我想让背景透明，让背后的设备也暴露出来，但是我找不到更改透明度的入口...

**Comment by monitor1394** [comment]
改颜色的alpha值为0

**Comment by kunlee1105** [comment]
> 改颜色的alpha值为0

我好像没看到有这个api...能指出在哪里吗，感谢

**Comment by monitor1394** [comment]
代码大概可以这样：

> var color = chart.themeInfo.backgroundColor;
> color.a = 0;//0-255
> chart.themeInfo.backgroundColor = color;

不能直接设置为Color.clear，设置为Color.clear时表示取自默认主题的颜色。
`
