### ISSUE TITLE
发布时有几处跟Editor有关的错误

### ISSUE THREAD

**Issue by StudentYan-Ling** [monitor1394/unity-ugui-XCharts#5]
Series Radar JsonDataSupport三个是代码里引用了UnityEditor的命名空间，但是没有使用，我直接删除了，还有CoordinateChart和LineChart是因为重写了BaseChart的Reset方法，BaseChart的Reset方法加了#if UNITY_EDITOR，但是子类的Reset没有加#if UNITY_EDITOR，发布时会因为找不到重写的方法报错，这个我在子类的Reset方法也加了#if UNITY_EDITOR。
这几个小问题处理完了之后可以成功发布，但编辑器里还是会有两个错误，好像是绘图相关的。
希望大佬有时间修复一下，或者我可以把我的改动提交

**Comment by monitor1394** [comment]
好的，发布这块还没有测试过，这两天我测下发布并把问题都处理下。非常感谢您的反馈。

**Comment by monitor1394** [comment]
打包问题已修复，在Unity 2017.2.0f3，三星S8上测试正常。
