### ISSUE TITLE
Change format of big numbers

### ISSUE THREAD

**Issue by samorogu** [monitor1394/unity-ugui-XCharts#50]
First of all, thanks for your time developing such a great tool to display 2d graphs.

I'm having trouble to display big numbers in a formatted way. It would be nice if the string showed when hovering some data point could be shown as: "1,345,000.0" instead of "1345000.0", for example.

Do you know in which of the scripts I can achive this?

**Comment by monitor1394** [comment]
You can modify ChartCached.cs by yourself, all the numbers to string is cached in ChartCached.

> `ChartCached.IntToStr()`
> `ChartCached.FloatToStr()`

In later versions, I will add a parameter to support this formatter.

Thanks for your advice.

**Comment by monitor1394** [comment]
I'm refactoring the code to support all the standard number format strings, which will take me a fews days.
A parameter called `numericFormatter` will be provided on `AxisLabel`, `SerieLabel` and `Tooltip`.

**Comment by samorogu** [comment]
It would be a nice and useful feature.

Thanks in advance!

**Comment by monitor1394** [comment]
The master branch has supported setting the `numericFomatter` parameter.
You can set it in `AxisLabel`,  `SerieLabel`, `Tooltip` and `ItemStyle`.

**Comment by samorogu** [comment]
I will try the functionality, thank you!
