### ISSUE TITLE
发现一个XChart图表赋值 Stack empty的问题

### ISSUE THREAD

**Issue by leonwxy** [monitor1394/unity-ugui-XCharts#51]
![image](https://user-images.githubusercontent.com/50473557/81638163-cf9ec100-944a-11ea-9905-8dc13a731b73.png)
![image](https://user-images.githubusercontent.com/50473557/81638203-ed6c2600-944a-11ea-9200-2bb5cfa5166f.png)

**Comment by monitor1394** [comment]
这个是你加的测试代码吧，XCharts上没有这个if判断的。

**Comment by leonwxy** [comment]
我已经取消了 这个确实是我们项目自己加的 我搞错了

monitor1394 <notifications@github.com> 于2020年5月12日周二 下午2:00写道：
