### ISSUE TITLE
tooltips 的 numericformatter 目前只对 {c} 起作用，{d} 不起作用

### ISSUE THREAD

**Issue by Bian-Sh** [monitor1394/unity-ugui-XCharts#54]
#rt 
>问题一：

numericformatter 只对itemformatter {c} 起作用，{d} 不起作用
>问题二：

在tooltip上，numericformatter 目前只能一对多，但这是有问题的：
比如{c} 为人数，{d}为百分比 ，当我想要百分比保留2位小数，那么此时 人数会出现 4.00人 这样的奇怪情况。

## 综上:

建议让{c} {d} 支持 {c:f2} {d:f2} 这种写法 ，方便联想，也保持了 ToString API 种formatter 的用户使用惯性，解决了上面提到的 numericformater 面临一对多时出现的问题

**Comment by monitor1394** [comment]
master已支持{c1:1-1:f1}类型的格式设置，具体请看Tooltip的formatter。
