### ISSUE TITLE
更新piechart数据时theme有问题

### ISSUE THREAD

**Issue by moonforce** [monitor1394/unity-ugui-XCharts#55]
使用ClearData清空数据，再使用AddData增加数据，piechart各分块的颜色都是theme中ColorPalette的第一个。

**Comment by monitor1394** [comment]
检查下添加数据的name是否一致了。或者发一下你的代码。

**Comment by moonforce** [comment]
UpdateDuiChangPieChart(m_DuiChangPieChart, fHeavyCount, fEmptyCount, fNotUseCount, "重箱\n" + yards.F_RATE, "空箱\n" + yards.E_RATE, "未用\n" + (1 - fYardsPresentPercent).ToString("p"));

void UpdateDuiChangPieChart(PieChart duiChangPieChart, float fHeavyCount, float fEmptyCount, float fNotUseCount, string sHeavyCount, string sEmptyCount, string sNotUseCount)
    {
        duiChangPieChart.UpdateData(0, 0, fHeavyCount);
        duiChangPieChart.UpdateDataName(0, 0, sHeavyCount);
        duiChangPieChart.UpdateData(0, 1, fEmptyCount);
        duiChangPieChart.UpdateDataName(0, 1, sEmptyCount);
        duiChangPieChart.UpdateData(0, 2, fNotUseCount);
        duiChangPieChart.UpdateDataName(0, 2, sNotUseCount);
        duiChangPieChart.themeInfo.SetAllDirty();
        duiChangPieChart.RefreshChart();
    }

必须加duiChangPieChart.themeInfo.SetAllDirty();否则都是一个颜色。
是不是因为name改变了，所以要将themeInfo setDirty。

**Comment by monitor1394** [comment]
我测试了下，和themeInfo无关，之前是因为调用UpdateDataName时没有自动刷新，调用RefreshChart可以解决问题。
现在已经可以自动刷新了，不用再手动调RefreshChart。

**Comment by moonforce** [comment]
我测试还有问题，准确的说，而初始active状态为false的物体，UpdateDataName后，再将其显示，没有问题。
而初始active状态为true的物体，UpdateDataName后，必须调用themeInfo.SetAllDirty，即使调用RefreshChart，仍有下图问题。
![image](https://user-images.githubusercontent.com/10993776/83093783-b5174980-a0d2-11ea-8167-c3c607e40ccc.png)

**Comment by monitor1394** [comment]
“仍有下图的问题”是指什么问题，我看不出啥具体问题来。

**Comment by monitor1394** [comment]
现在你的代码是怎么样的

**Comment by moonforce** [comment]
![image](https://user-images.githubusercontent.com/10993776/83094082-6ae29800-a0d3-11ea-945d-3ac1a5580612.png)
正常现象如上。

**Comment by moonforce** [comment]
![image](https://user-images.githubusercontent.com/10993776/83095486-037a1780-a0d6-11ea-8b57-cf196b41d224.png)

**Comment by monitor1394** [comment]
你是更新master的最新版本了吧，我测试过没问题的

**Comment by moonforce** [comment]
是的，更新了最新版，说不定是unity版本问题2017.3.0f3 (64-bit)

**Comment by monitor1394** [comment]
问题修复了。
旧版本是因为没有显示legend引起的。

**Comment by moonforce** [comment]
测试已解决，多谢！
