### ISSUE TITLE
增加柱状图逐条渐现动画

### ISSUE THREAD

**Issue by muyifan** [monitor1394/unity-ugui-XCharts#58]
增加柱形图一根一根升起来的动画

**Comment by Bian-Sh** [comment]
> 增加柱形图一根一根升起来的动画

看能不能通过延迟一个一个数据的赋值实现一根根升起？没测试过你可以试试

**Comment by monitor1394** [comment]
> > 增加柱形图一根一根升起来的动画
> 
> 看能不能通过延迟一个一个数据的赋值实现一根根升起？没测试过你可以试试

目前的fadeInDelay是整体动画的延时，还无法配置单个数据的延时，需要开发下。

**Comment by monitor1394** [comment]
最新的master已支持。
`Animation`提供自定义数据项延时和时长回调函数，需要用代码设置。可以参考`Example03_ChartAnimation.cs`
