### ISSUE TITLE
PieChart 数据全是 0 图表会完全消失

### ISSUE THREAD

**Issue by Bian-Sh** [monitor1394/unity-ugui-XCharts#59]
嗨，小莫，
下图是我实际使用中遇到的 数据全是0的情况，图表消失不见（勾选Ignore value 只是决定了图表周边组件的显示隐藏）
![(}}}C4BMMH)55S9YFHXFV_D](https://user-images.githubusercontent.com/24520547/83939600-e00b4700-a810-11ea-9f11-d965bc6bbe45.png)
下图是 百度echart给出的方案，就是均分显示，数据标记为0 
![P(FRQV`BOLYDDA1H`SKG`YH](https://user-images.githubusercontent.com/24520547/83939604-e3063780-a810-11ea-9909-f61e43df413f.png)

yours

**Comment by monitor1394** [comment]
最新的master支持

**Comment by Bian-Sh** [comment]
> 最新的master已支持

nice，小莫辛苦了！
