### ISSUE TITLE
图例布局异常

### ISSUE THREAD

**Issue by Bian-Sh** [monitor1394/unity-ugui-XCharts#60]
现在这个Grid 自动布局以现有参数不能灵活的布局，可以考虑抽离出来一个Legend Grid 模块。
现在的体验是无论怎么调整，都调不到美术给的（合理需求）的图例布局
而且布局算法上应该存在问题，可能切换布局方式的时候没有合理换算，导致来回切换布局方式，图例调整的体验很诡异。

**Comment by monitor1394** [comment]
master上已更新修复。
