### ISSUE TITLE
如何对指定图表进行截图？ 

### ISSUE THREAD

**Issue by CGR-gio** [monitor1394/unity-ugui-XCharts#61]
因为计算数据后的图表结果出来了，然后需要截图作为文档保存，但是不知道应该怎么截图？感觉可以开发一个这样的功能吧。

**Comment by monitor1394** [comment]
暂无开发这个功能的计划。

**Comment by Bian-Sh** [comment]
> 因为计算数据后的图表结果出来了，然后需要截图作为文档保存，但是不知道应该怎么截图？感觉可以开发一个这样的功能吧。

可以试着自己写一个
