### ISSUE TITLE
编辑器上把图表的Series.Data 数量改为 0 会导致永远无法赋值的bug

### ISSUE THREAD

**Issue by Bian-Sh** [monitor1394/unity-ugui-XCharts#62]
rt
只要把图表的Series.Data 数量改为 0 ，再次通过改这个data size 来赋值的时候，就会报如下错误，且无法赋值，
![image](https://user-images.githubusercontent.com/24520547/84256451-7e1b4c00-ab46-11ea-82d8-03ea043801e1.png)
个人估计是再克隆上一个数据时没有确认上一个数据是否存在导致的。

**Comment by monitor1394** [comment]
已修复
