### ISSUE TITLE
piechart 绘制异常 

### ISSUE THREAD

**Issue by Bian-Sh** [monitor1394/unity-ugui-XCharts#65]
在配色存在半透明时可见piechart 绘制异常，测试跟gap 有一点关系，跟 border 没关系，异常效果如下：
![image](https://user-images.githubusercontent.com/24520547/84592829-ff424e00-ae7a-11ea-93c3-3689899ab1cc.png)

**Comment by monitor1394** [comment]
测试发现serie的clockwise为false，估计是代码设置了。PieChart目前只支持顺时针。master已处理提交了。

**Comment by Bian-Sh** [comment]
测试已解决问题
