### ISSUE TITLE
Label属性里面的formatter里的数值精度如何单独设置

### ISSUE THREAD

**Issue by LONG9361** [monitor1394/unity-ugui-XCharts#68]
目前Label属性里的format属性里的数值可以通过Numeric Formatter格式化数字精度，但是会应用到说有的数字上，比如有个数据：
数据名：{b}（{c}）\n{d},c的值是整数，目前d的值是百分比，但是小数数位太多， 使用Numeric Formatter P2，c和d的值都变成百分比

**Comment by LONG9361** [comment]
Numeric Formatter G系列可以解决问题

**Comment by LONG9361** [comment]
SerieLabaleHelper.cs文件中第106行可以自行添加过滤

**Comment by monitor1394** [comment]
确实应该要可以单独设置，后面会优化成和Tooltip一样可任意设置精度。

**Comment by monitor1394** [comment]
master已支持，numericFormatter控制所有，{c:f2}可以单独指定。
