### ISSUE TITLE
X、Y轴均为log类型，添加了数据之后，数据都显示到坐标轴上了？

### ISSUE THREAD

**Issue by oldeone** [monitor1394/unity-ugui-XCharts#70]
X、Y轴均为log类型，添加了数据之后，可以在inspector面板里看到数据已经正常读取到linechart的serie中，但是在图上却全都跑到接近（0,0）的位置了。不知道这是什么原因呢
![001](https://user-images.githubusercontent.com/49703045/86700467-b88fe000-c043-11ea-8e33-4e0ea543d838.PNG)
![002](https://user-images.githubusercontent.com/49703045/86700476-ba59a380-c043-11ea-91fc-84155ec1d6ee.PNG)

**Comment by monitor1394** [comment]
经测试，XY都为Log轴的情况下绘制正常。你的问题我也不清楚什么原因，可以的话麻烦放出相关代码。
<img width="266" alt="image" src="https://user-images.githubusercontent.com/1450329/86855846-c437e100-c0ed-11ea-8b12-90d41981d1f4.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1450329/86855860-ce59df80-c0ed-11ea-9048-c6b3473a162a.png">

**Comment by oldeone** [comment]
`public LineChart lineChart_mathews;

    void Start()
    {

        Debug.Log("采空区一共有：" + StaticParams.globalParams.Count + "个，其中有Mathew图计算参数的采空区一共有：" + StaticParams.mathewParams.Count+ "个");

        //设置标题
        lineChart_mathews.title.show = true;
        lineChart_mathews.title.textStyle.fontSize = 30;
        lineChart_mathews.title.textStyle.color = Color.green;
        lineChart_mathews.title.text = "Mathews稳定图";

        //使用提示框
        lineChart_mathews.tooltip.show = true;
        lineChart_mathews.tooltip.type = Tooltip.Type.Corss;
        lineChart_mathews.tooltip.itemFormatter = "{.}{a}\n{b}{c}\n换行显示测试\n再换行显示测试";

        //使用图例
        lineChart_mathews.legend.show = false;
        //使用X、Y主轴
        lineChart_mathews.xAxises[0].show = true;
        lineChart_mathews.xAxises[1].show = false;
        lineChart_mathews.yAxises[0].show = true;
        lineChart_mathews.yAxises[1].show = false;
        //设置轴类型（Value、Category两种）
        lineChart_mathews.xAxises[0].type = Axis.AxisType.Log;
        lineChart_mathews.yAxises[0].type = Axis.AxisType.Log;
        //坐标轴刻度最大最小值显示类型
        lineChart_mathews.xAxises[0].minMaxType = Axis.AxisMinMaxType.Custom;
        lineChart_mathews.xAxises[0].min = 1;
        lineChart_mathews.xAxises[0].max = 100;
        lineChart_mathews.yAxises[0].minMaxType = Axis.AxisMinMaxType.Custom;
        lineChart_mathews.yAxises[0].min = 0.001f;
        lineChart_mathews.yAxises[0].max = 1000;
        lineChart_mathews.xAxises[0].axisLine.onZero = false;
        //轴标签位于轴标记下方
        lineChart_mathews.xAxises[0].axisTick.alignWithLabel = true;
        //轴分割段数
        lineChart_mathews.xAxises[0].splitNumber = 3;
        lineChart_mathews.yAxises[0].splitNumber = 6;
        //坐标轴两边是否留白
        lineChart_mathews.xAxises[0].boundaryGap = false;
        //清除所有数据
        lineChart_mathews.RemoveData();

        //mathews图边界线数据
        //稳定-破坏边界
        float[] stable_destroy_data = { 1, 0.204f, 36, 142.12f };
        //破坏-崩落边界
        float[] destroy_drop_data = { 1, 0.001f, 36, 0.66127f };

        //lineChart_mathews

        //添加数据系列
        //稳定-破坏边界
        lineChart_mathews.AddSerie(SerieType.Line, "稳定-破坏线");
        //破坏-崩落边界
        lineChart_mathews.AddSerie(SerieType.Line, "破坏-崩落线");
        //围岩稳定数值
        lineChart_mathews.AddSerie(SerieType.Scatter, "围岩稳定数值");
        for (int i = 0; i < 2; i++)
        {
            lineChart_mathews.series.GetSerie(i).symbol.type = SerieSymbolType.None;
        }
        lineChart_mathews.series.GetSerie(2).symbol.type = SerieSymbolType.Circle;
        lineChart_mathews.series.GetSerie(2).symbol.size = 5;
        lineChart_mathews.series.GetSerie(2).symbol.selectedSize = 8;

        lineChart_mathews.AddData("稳定-破坏线", stable_destroy_data[0], stable_destroy_data[1], "稳定-破坏线1");
        lineChart_mathews.AddData("稳定-破坏线", stable_destroy_data[2], stable_destroy_data[3], "稳定-破坏线1");
        lineChart_mathews.AddData("破坏-崩落线", destroy_drop_data[0], destroy_drop_data[1], "破坏-崩落线1");
        lineChart_mathews.AddData("破坏-崩落线", destroy_drop_data[2], destroy_drop_data[3], "破坏-崩落线1");

        for (int i = 0; i < StaticParams.mathewParams.Count; i++)
        {

            //float xValue = Mathf.Exp (mathewParams[i].ShapeFactor);
            //float yValue = Mathf.Exp (mathewParams[i].GravityAdjustmentIndex);
            float xValue = StaticParams.mathewParams[i].ShapeFactor;
            float yValue = StaticParams.mathewParams[i].StableParam;
            //float xValue = Mathf.Pow(10, StaticParams.mathewParams[i].ShapeFactor);
            //float yValue = Mathf.Pow(10, StaticParams.mathewParams[i].StableParam);
            //float xValue = Mathf.Log(mathewParams[i].ShapeFactor);
            //float yValue = Mathf.Log(mathewParams[i].GravityAdjustmentIndex);
            string dataName = StaticParams.mathewParams[i].Location;
            Debug.Log("第"+i+"组数据"+"(" + xValue + "," + yValue + ")");
            lineChart_mathews.AddData(2, xValue, yValue, dataName);
        }
    }`

**Comment by monitor1394** [comment]
嗯，知道问题了，Scatter还不支持Log轴，我有空处理下。

**Comment by monitor1394** [comment]
master已修复提交。
