### ISSUE TITLE
当图表上层有窗口时，触摸上层窗口会触发下层图表的Tooltip显示

### ISSUE THREAD

**Issue by ShaoGuanghe** [monitor1394/unity-ugui-XCharts#74]
我在图表（XChart）上层放了一个窗口，当我点击窗口时，触摸时间会穿透到下层图表，从而触发下层图表的Tooltip显示。我希望上层窗口能拦截触摸事件，不触发下层Tooltip显示。
![截屏2020-07-15 下午9 48 38](https://user-images.githubusercontent.com/68337704/87555937-a586ab00-c6e8-11ea-975a-cbc2fb691282.png)
如图所示，当我点击箭头所在位置时，下层图表会显示Tooltip。

**Comment by monitor1394** [comment]
已修复。
