### ISSUE TITLE
折线图数据太多报ArgumentException: Mesh can not have more than 65000 vertices 错误

### ISSUE THREAD

**Issue by liaoyanping** [monitor1394/unity-ugui-XCharts#76]
折线图数据太多报ArgumentException: Mesh can not have more than 65000 vertices 错误

**Comment by monitor1394** [comment]
看[XCharts问答](https://github.com/monitor1394/unity-ugui-XCharts/blob/master/Assets/XCharts/Documentation/XCharts问答.md)   的QA 27：Mesh can not have more than 65000 vertices?
