### ISSUE TITLE
RadarChart tooltips  好像还不能用

### ISSUE THREAD

**Issue by Bian-Sh** [monitor1394/unity-ugui-XCharts#77]
发现 雷达图的 tooltips 不能用，望加上。
另外，默认的tooltips 布局不符合需求，我们这边需要展示的是各个圈落在同一个轴向上的数据。
示意图如下：
![image](https://user-images.githubusercontent.com/24520547/88144621-d0fb1f80-cc2b-11ea-819d-df49e62af429.png)

类似于Linechart，示意图如下：
![image](https://user-images.githubusercontent.com/24520547/88144699-ed975780-cc2b-11ea-8cd2-41f716436434.png)

初步可能tooltips itemformatter = {b}{c} 或 {a}{c} 或{a0}{c0}\n{a1}{c1} 或 {b0}{c0}\n{b1}{c1}

**Comment by monitor1394** [comment]
master已更新。
对于Multiple类型的雷达图，默认tooltip显示一圈的数据，可通过Radar的isAxisTooltip参数控制是否显示轴线上的数据。
对于Single类型的雷达图，默认就是显示轴线上的数据。

**Comment by Bian-Sh** [comment]
小莫辛苦了！
刚简单测试了发现以下问题：
1. Tooltips 格式化规则中不支持 Indicator 
2. Tooltips默认配置下，使用2组serie 每个serie dimension 不同的情况下，会出现 tooltips 表现形式不一样的情况，效果如下：
![image](https://user-images.githubusercontent.com/24520547/88750450-284b4380-d188-11ea-9a42-ebc990c97a57.png)
![image](https://user-images.githubusercontent.com/24520547/88750475-339e6f00-d188-11ea-8a7b-453ba4fd2881.png)
 每个serie dimension 相同的情况下不会出现。
3. 另外，在勾选了 isAxisTooltips 后，挪到Symbol 上时，体验上个人建议应该是这个轴上的Symbo 都被highlight 而不是某一圈的Symbol 被highlight，否则会用户的困惑。
4. 然后 tooltips formatter 是 {b} 时，第二个series的数据的名称是第一个数据的名称，自己的数据项名称 不凑效
下面是 Preset文件，导入即可测试：
[RadarChart07291.zip](https://github.com/monitor1394/unity-ugui-XCharts/files/4992302/RadarChart07291.zip)

**Comment by monitor1394** [comment]
1. tooltip的formatter不支持indicator，当无formatter时优先取serieData的name，否则取indicator。
2. 由用户自己保证数据的正确和合理性。不同dimension的数据不应该放在同一个Radar。
3. 已更新支持。
4. 你应该用itemFormatter。formatter的{b}其实是{b0}，formatter必须完全自定义。
