### ISSUE TITLE
画布渲染模式选择第二种摄像机渲染tooltip的显示有问题

### ISSUE THREAD

**Issue by SerbiaKelly** [monitor1394/unity-ugui-XCharts#8]
运行时会自动的设置回代码里的默认参数配置,可以关掉这个吗?

**Comment by monitor1394** [comment]
感谢反馈，我稍后确认下这个问题

**Comment by monitor1394** [comment]
关于tooltip在Screen Space-Camera模式下显示问题已修复。

关于第二个问题，是哪些设置被运行时重设了？理论上关于chart的设置都是会保存的。

**Comment by SerbiaKelly** [comment]
第二个问题是我看错了,不好意思

**Comment by monitor1394** [comment]
好的没问题就关了
