### ISSUE TITLE
水位图BUG

### ISSUE THREAD

**Issue by shenhuilin** [monitor1394/unity-ugui-XCharts#80]
![O~M8JK`D6 C(H@1SPG0IC(0](https://user-images.githubusercontent.com/31879581/88364477-9c1ad400-cdb5-11ea-8245-bdbdf82c0f87.png)

水位图值没有到最大值的情况下，渐变正常。
![)_6OSHS3ZMO}%R2`KE `BXG](https://user-images.githubusercontent.com/31879581/88364515-b8b70c00-cdb5-11ea-98a2-3bfa50cf1714.png)
值等于或超过最大值就会变成纯色，label也会消失

**Comment by monitor1394** [comment]
master已修复。
