### ISSUE TITLE
x轴的坐标点固定时，往表格加值绘制出来的曲线会铺满表格

### ISSUE THREAD

**Issue by seriousuncle** [monitor1394/unity-ugui-XCharts#87]
现在想做一个实时往表格赋值的功能，demo里面有类似效果，但是在点还没有达到最大值的时候，就将点平均分布在整个表格上了；试过将x轴坐标系写死，往里面赋二维数组来解决这个问题，但是这样会出现画了点但是不绘制曲线的问题。

**Comment by monitor1394** [comment]
不太明确你的需求，最好发一下效果图。大概是你可以先添加0的数据占位，再通过UpdateData更新实际的值。
