### ISSUE TITLE
如果XAxis的type设置为value，YAxis的type也为value时，Y的MinMaxType为Custom时，Y轴调节Min，Max的值没用

### ISSUE THREAD

**Issue by huhonglei** [monitor1394/unity-ugui-XCharts#9]
如果XAxis的type设置为value，YAxis的type也为value时，Y的MinMaxType为Custom时，Y轴调节Min，Max的值没用。他的值好像和X轴的会一样。

**Comment by huhonglei** [comment]
好像发现 X，Y不能同时设置type为Value，这个问题大佬能看看么

**Comment by monitor1394** [comment]
XY轴都设置为Value目前确实是不支持，主要是Serie的data现在是一维数组，需要改为二维数组。这个功能已在开发计划中。

**Comment by monitor1394** [comment]
XY轴同时设置为Value数值轴的功能已实现，可以更新最新代码测试下。
