### ISSUE TITLE
1.6.0 Package Manager版導入失效

### ISSUE THREAD

**Issue by jonjongao** [monitor1394/unity-ugui-XCharts#92]
您好，我嘗試以pacakge方式更新到1.6.0版不過導入卻不成功，許多代碼因為缺少meta的關係被忽視。我試過刪掉整個包並重新下載package也不行
我返回我上一個使用版本1.5.2確認在那時代碼確實是還有meta的，不過到1.6.0就缺meta了
![Imgur](https://i.imgur.com/uzlRRUE.png)

**Comment by monitor1394** [comment]
好的，谢谢反馈，我尽快处理

**Comment by monitor1394** [comment]
下个版本修复，这两天新版本发布。

**Comment by monitor1394** [comment]
v1.6.1版本已发布
