### ISSUE TITLE
折线图，图例和X轴的名字对不上

### ISSUE THREAD

**Issue by shenhuilin** [monitor1394/unity-ugui-XCharts#93]
![@TL@SZ1VVR(DED5YHZ0I}26](https://user-images.githubusercontent.com/31879581/93455661-3bb89680-f90f-11ea-999b-20d485cea3a5.png)
![AE0EJSZE5KWX3}1U$UB5L N](https://user-images.githubusercontent.com/31879581/93455676-3eb38700-f90f-11ea-86ec-f195cf854090.png)

**Comment by monitor1394** [comment]
master已修复。
