### ISSUE TITLE
关于LineChart中对数(log)显示的两个bug

### ISSUE THREAD

**Issue by GOUBIN** [monitor1394/unity-ugui-XCharts#96]
bug1:
当折线图切换到log模式后,折线图的splitNumber参数无法进行修改
bug2:
当折线图切换到log模式后,如果将LogBase参数改为0,会直接卡死

**Comment by monitor1394** [comment]
关于bug1，对数轴有一定的条件限制，不能任意设置splitNumber，不知你想要什么样的效果，我再根据效果看怎么优化。
关于bug2，master已简单处理防止卡死。但数据的正确性需要用户自己保证，比如数据都是大于1的数据时，不应该设置logBase为小于1的底数。
