### ISSUE TITLE
Chart元件於Inspector上的Properties在一定範圍外顯示異常

### ISSUE THREAD

**Issue by GooKu** [monitor1394/unity-ugui-XCharts#97]
Unity版本: 2020.1.6f1
在Inspector上展開各類Chart元件的Properties時, 在一定的長度之後的Properties無法正常顯示, 會被下方的component給蓋過
此時沒有手段(ex: scroll bar, 滑鼠滾輪)能夠查看/設定Inspector上超出顯示範圍的Properties

![image](https://user-images.githubusercontent.com/8335757/95058313-ec090600-0729-11eb-9598-6f8403861717.png)

**Comment by monitor1394** [comment]
我在2020.1.6f1上测试没碰到你反馈的问题。其他版本也是这样吗

**Comment by GooKu** [comment]
我亦有在2019.4.9f1上跑, 但未見此問題

**Comment by monitor1394** [comment]
这个看着像Unity的问题。可以尝试换个版本。

**Comment by GooKu** [comment]
了解 我就把這結了
