### ISSUE TITLE
折线图的长或宽如果不够，数据会凸出来

### ISSUE THREAD

**Issue by PHNoob** [monitor1394/unity-ugui-XCharts#99]
图一是正常情况，图二为同一组数据但缩短折线图的长(宽)。
![QJ )TS3$Y H`$9@}JI0 DLI](https://user-images.githubusercontent.com/49261291/97828034-ea1e6c80-1d00-11eb-80af-c4e8df71e9d4.png)
![JG7EL6SF_ PZJ7@DXK~97KT](https://user-images.githubusercontent.com/49261291/97828070-03271d80-1d01-11eb-85f8-aff08972f9df.png)

**Comment by monitor1394** [comment]
是的，数据过密且波峰波谷差异太大时可能会出现这种问题，后续版本再修复了，目前不太好解决。

**Comment by monitor1394** [comment]
修复了。
